### ISSUE TITLE
gitignore needs *.csproj

### ISSUE THREAD

**Issue by Brickcaster** [magico13/ScrapYard#1]
In forking I had to update the project with my local location of the Kerbal dll files.  If I were to create a pull request, I wouldn't want to include this file in the request.

I'm not familiar enough with git to figure out how to modify the gitignore without doing a fork/edit/commit/pull so maybe it'd just be simpler if you could push a commit on your end.

**Comment by magico13** [comment]
You can just exclude your changes or I can handle it during the merge. If
you add/remove files the csproj needs to be updated, so I don't think
ignoring it is the right solution. I also need it if I set up continuous
integration.

If you don't add any new files, then just exclude it from the commit.
Otherwise I'll just handle it during the PR.
